/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect.sgbd;

import Clase.Tabele;
import Date.DateTabele;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AdaugaCheieStraina extends javax.swing.JFrame {

    /**
     * Creates new form AdaugaCheieStraina
     */
    public AdaugaCheieStraina() throws SQLException {
        initComponents();
        setVisible(true);
        setResizable(false);
        afiseazaTabele();
        setTitle("DBMS-JAVA-Normalizarea-cheilor-straine");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        StangaNume = new javax.swing.JComboBox<>();
        DreaptaCol = new javax.swing.JComboBox<>();
        DreaptaNume = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StangaCol = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Adauga cheie straina:");

        jButton1.setText("Adauga cheie straina");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tabel:");

        jLabel3.setText("Coloana:");

        jLabel4.setText("Coloana:");

        jLabel5.setText("Coloana:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StangaNume, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(DreaptaNume, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StangaCol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DreaptaCol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DreaptaCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StangaCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StangaNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DreaptaNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Tabel1 = StangaCol.getSelectedItem().toString();
        String Tabel2 = DreaptaCol.getSelectedItem().toString();
        String col1 = StangaNume.getSelectedItem().toString();
        String col2 = DreaptaNume.getSelectedItem().toString();
        int p = DateTabele.verificareCheieStraina(Tabel1,Tabel2,col1,col2);
        System.out.println(p);
        if(p == 1)
        {
            int adaugaCheie = DateTabele.adaugaCheieStraina(Tabel1,Tabel2,col1,col2);
            if (adaugaCheie == 1 )
            {
                JOptionPane.showMessageDialog(null, "Referinta adaugata cu succes." , "Eroare", JOptionPane.INFORMATION_MESSAGE);
            }
            else 
            {
                JOptionPane.showMessageDialog(null, "Constrangere existenta." , "Eroare", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        else if(p == -1)
        {
            JOptionPane.showMessageDialog(null, "Nu a fost găsit niciun Index unic pentru campul la care se face referire din tabelul principal. ", "Eroare", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Coloanele selectate nu au acelasi tip de date." , "Eroare", JOptionPane.INFORMATION_MESSAGE);
        }
               
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugaCheieStraina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugaCheieStraina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugaCheieStraina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugaCheieStraina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdaugaCheieStraina().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdaugaCheieStraina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void afiseazaTabele() throws SQLException
    {
        
        for (Tabele item : DateTabele.listaNumeTabele()) 
        {
            StangaCol.addItem(String.valueOf(item.getNumeTabele()));
           // DreaptaCol.addItem(String.valueOf(item.getNumeTabele()));
        }
        
        StangaCol.addActionListener (new ActionListener () 
        {
            public void actionPerformed(ActionEvent e) 
            {
                StangaNume.removeAllItems();
                try 
                {
                    for (Tabele tabel : DateTabele.detaliiTabel(StangaCol.getSelectedItem().toString()))
                    {
                        String numeColoane[] = {String.valueOf(tabel.getNumeColoana()),};
                        String nColoane = numeColoane[0];
                        StangaNume.addItem(nColoane);  
                    }  
                    String evitaDuplicat = StangaCol.getSelectedItem().toString();
                    for (Tabele item : DateTabele.listaNumeTabele()) 
                    {
                        if(evitaDuplicat.equals(String.valueOf(item.getNumeTabele())))
                        {}
                        else
                         DreaptaCol.addItem(String.valueOf(item.getNumeTabele()));
                    }
                } 
                catch (SQLException ex) 
                {
                    Logger.getLogger(AdaugaCheieStraina.class.getName()).log(Level.SEVERE, null, ex);
                }
     
                
            }
        });
       
        
        DreaptaCol.addActionListener (new ActionListener () 
        {
            public void actionPerformed(ActionEvent e) 
            {
                DreaptaNume.removeAllItems();
                try 
                {
                    for (Tabele tabel : DateTabele.detaliiTabel(DreaptaCol.getSelectedItem().toString()))
                    {
                        String numeColoane[] = {String.valueOf(tabel.getNumeColoana()),};
                        String nColoane = numeColoane[0];
                        DreaptaNume.addItem(nColoane);
                    }   
                } 
                catch (SQLException ex) 
                {
                    Logger.getLogger(AdaugaCheieStraina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DreaptaCol;
    private javax.swing.JComboBox<String> DreaptaNume;
    private javax.swing.JComboBox<String> StangaCol;
    private javax.swing.JComboBox<String> StangaNume;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
