/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect.sgbd;

import Clase.Tabele;
import Date.DateTabele;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static net.ucanaccess.converters.Functions.str;
import static proiect.sgbd.PaginaPrincipala.ListaTabele;



/**
 *
 * @author petri
 */
public class Indexuri extends javax.swing.JFrame {
    DefaultTableModel TabelIndex = new DefaultTableModel();
    public Indexuri() {
        String numeTabel = PaginaPrincipala.numeTabelIndex;
        setResizable(false);
        String coloane[] = {"Nume Index","Nume coloana","  "};
        TabelIndex.setColumnIdentifiers(coloane);
        initComponents();
        String[] constrangere = { "PRIMARY KEY" , "UNIQUE"} ;
        selectareConstrangere.setModel(new DefaultComboBoxModel(constrangere));
        tabelIndex.setRowHeight(20);       
        adaugareColoana.removeAllItems();
        try 
        {
            for (Tabele tabel : DateTabele.listaColoane(numeTabel))
            {
                adaugareColoana.insertItemAt(String.valueOf(tabel.getlistaColoane()), 0);
                adaugareColoana.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
                tabelIndex.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(adaugareColoana));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Indexuri.class.getName()).log(Level.SEVERE, null, ex);
        }
        selectareConstrangere.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
        tabelIndex.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(selectareConstrangere));
        numeTabel2.setText(numeTabel);
        adaugaIndexTabel();
        setVisible(true);
        setTitle("DBMS-JAVA-Normalizarea-cheilor-straine");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectareConstrangere = new javax.swing.JComboBox<>();
        adaugareColoana = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelIndex = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numeTabel2 = new javax.swing.JLabel();

        selectareConstrangere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        adaugareColoana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelIndex.setModel(TabelIndex);
        jScrollPane1.setViewportView(tabelIndex);

        jButton1.setText("Adauga INDEX");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sterge INDEX");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Indexuri tabel:  ");

        numeTabel2.setText("numeTabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeTabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeTabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numeTabel = PaginaPrincipala.numeTabelIndex;
        int rand = tabelIndex.getSelectedRow();
        System.out.println(numeTabel + " " +  rand);
        int rand2 = tabelIndex.getRowCount()-1;
        if(rand == rand2)
        {
            String numeConstrangere = tabelIndex.getValueAt(rand,0).toString();
            adaugaIndexTabel();
            String coloana = adaugareColoana.getSelectedItem().toString();
            System.out.println(coloana + " " + numeConstrangere );
            if(selectareConstrangere.getSelectedItem().toString().equals("UNIQUE"))
            {
                 JOptionPane.showMessageDialog(null, DateTabele.adaugaUnique(numeTabel, coloana, numeConstrangere));
            }  
            else if(selectareConstrangere.getSelectedItem().toString().equals("PRIMARY KEY"))
            {
                 JOptionPane.showMessageDialog(null, DateTabele.adaugaPrimary(numeTabel, coloana, numeConstrangere));
            }  
        }  
        if(rand >=0)
        {
            
        }
        else{
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String numeTabel = PaginaPrincipala.numeTabelIndex;
        String numeIndex = tabelIndex.getValueAt(tabelIndex.getSelectedRow(), 0).toString();
        if(selectareConstrangere.getSelectedItem().toString().equals("PRIMARY KEY"))
            {
                 JOptionPane.showMessageDialog(null, DateTabele.stergePrimary(numeTabel,numeIndex));
            } 
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void adaugaIndexTabel()
    {
        String numeTabel = PaginaPrincipala.numeTabelIndex;
        DateTabele.indexTabel(numeTabel);
        while (TabelIndex.getRowCount() > 0) 
            {
                TabelIndex.removeRow(0);
            }
            for (Tabele tabel : DateTabele.indexTabel(numeTabel))
            {
                String cheieFK[] = {String.valueOf(tabel.getNumeIndex()),};
                String cheiePK[] = {String.valueOf(tabel.getColoanaIndex()),};
                String TabelReferit[] = {String.valueOf(tabel.getTipIndex()),};
                String cheieFK1 = cheieFK[0];
                String pk = cheiePK[0];
                String tabelReferit = TabelReferit[0];
                TabelIndex.addRow(new Object[]{ cheieFK1,pk , tabelReferit });
                //TabelIndex.addRow(new Object[]{ pk , tabelReferit});
            }
        TabelIndex.addRow(new Object[] {"","",""});
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indexuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indexuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indexuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indexuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Indexuri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adaugareColoana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeTabel2;
    private javax.swing.JComboBox<String> selectareConstrangere;
    private javax.swing.JTable tabelIndex;
    // End of variables declaration//GEN-END:variables
}
